### ISSUE TITLE
Occasional JSF issue when going through the JWT guide

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/guide-microprofile-jwt#37] opened 2018-04-19 13:39 UTC
Sometimes there is something bad cached in the browser such that a JSF exception occurs when you try to login to the frontendUI.
 
The message is (something like) `No such view state found`. Exception was on customer machine but @Emily-Jiang has seen it too.

Switching to a private browser window (i.e. no cache or cookies) solves the problem.

**Comment by evelinec** [comment] 2018-05-22 17:57
@JunyiSun to provide guidance for @proubatsis to work on this issue.

**Comment by proubatsis** [comment] 2018-05-22 20:26
@tevans78 I can't seem to reproduce this issue, can you provide any more details on what steps were taken to make this happen?

**Comment by tevans78** [comment] 2018-05-23 08:56
Unfortunately I have only ever seen this on other people's machines. @Emily-Jiang says she saw the issue too so perhaps she can provide a little more information?

**Comment by proubatsis** [comment] 2018-05-23 13:57
I believe that I reproduced the problem, but it says `No saved view state could be found for the view identifier` instead of `No such view state found`. Can you confirm this is the same issue you were experiencing please @tevans78 ?

![image](https://user-images.githubusercontent.com/8409464/40428919-673f3e40-5e6f-11e8-8b4c-0f5a9b073ee5.png)

**Comment by proubatsis** [comment] 2018-05-23 20:38
#47

**Comment by JunyiSun** [comment] 2018-05-31 20:39
reviewed and merged.

**Comment by yeekangc** [comment] 2018-09-20 15:07
Looks like this issue may not have been fully fixed.  Just ran into it.

**Comment by proubatsis** [comment] 2018-10-17 17:35
PR Merged.

**Closed** 2018-10-25 15:08 UTC
Labels: static
